apiVersion: v1
kind: ConfigMap
metadata:
  name: ebpf-config
  namespace: kube-system
data:
  enabled_tracers: |
    - swaphist.py
    - oom_tracer.py
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-debugger
  namespace: kube-system
spec:
  selector:
    matchLabels: { app: node-debugger }
  template:
    metadata:
      labels: { app: node-debugger }
    spec:
      hostPID: true
      tolerations:
      - operator: "Exists"
      containers:
      - name: ebpf-tracer
        image: gcr.io/ajaysundar-gke-multi-cloud-dev/hack/ebpf-tools:0.5
        securityContext:
          privileged: true   # required for bpf
        volumeMounts:        # Mount necessary host paths for BCC/eBPF to function
        - { name: lib-modules,  mountPath: /lib/modules, readOnly: true }
        - { name: sys-kernel-debug,  mountPath: /sys/kernel/debug, readOnly: true }
        - { name: tracer-config,  mountPath: /etc/ebpf, readOnly: true }
      initContainers:
      - name: mcp-server
        image: gcr.io/ajaysundar-gke-multi-cloud-dev/hack/gke-node-mcp-server:0.5
        ports:
        - containerPort: 3200
      - name: node-collector
        image: gcr.io/ajaysundar-gke-multi-cloud-dev/hack/nodecollector:0.5
        restartPolicy: Always
        securityContext:
          privileged: true   # required for /proc access
        ports:
        - containerPort: 3100
        volumeMounts:
        - { name: proc,  mountPath: /proc, readOnly: true }
        - { name: cgv2,  mountPath: /sys/fs/cgroup, readOnly: true }
      volumes:
      - { name: proc, hostPath: { path: /proc } }
      - { name: cgv2, hostPath: { path: /sys/fs/cgroup } }
      - { name: lib-modules, hostPath: { path: /lib/modules } }
      - { name: sys-kernel-debug, hostPath: { path: /sys/kernel/debug } }
      - name: tracer-config
        configMap:
          name: ebpf-config
          items:
          - key: enabled_tracers
            path: config.yaml
